name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily

  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v2
        with:
          github_user_name: LEAKONO  # Change this to your GitHub username
          outputs: github-contribution-grid-snake.svg
      - uses: actions/upload-artifact@v3
        with:
          name: snake
          path: github-contribution-grid-snake.svg
